// <auto-generated />
namespace GuildCars.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3717 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3717));
        
        string IMigrationMetadata.Id
        {
            get { return "201703071955549_3-7-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
