USE GuildCars
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Contact')
	DROP TABLE Contact 
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Purchase')
	DROP TABLE Purchase
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Vehicle')
	DROP TABLE Vehicle
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Model')
	DROP TABLE Model
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Make')
	DROP TABLE Make
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Special')
	DROP TABLE Special
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Customer')
	DROP TABLE Customer
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='InteriorColor')
	DROP TABLE InteriorColor
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='BodyColor')
	DROP TABLE BodyColor
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='Transmission')
	DROP TABLE Transmission
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='BodyStyle')
	DROP TABLE BodyStyle
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='State')
	DROP TABLE [State] 
GO

CREATE TABLE [State] (
	StateID CHAR(2) PRIMARY KEY NOT NULL,
	StateName VARCHAR(15) NOT NULL
	)
GO

CREATE TABLE BodyStyle (
	BodyStyleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	BodyDescription VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE Transmission (
	TransmissionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Gears VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE BodyColor (
	BodyColorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	BodyColorName VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE InteriorColor (
	InteriorColorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	InteriorColorName VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE Customer (
	CustomerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FullName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(30) NULL,
	Phone VARCHAR(24) NULL,
	Street1 NVARCHAR(30) NOT NULL,
	Street2 NVARCHAR(30) NULL,
	City NVARCHAR(15) NOT NULL,
	[State] CHAR(2) NOT NULL FOREIGN KEY REFERENCES [State](StateID),
	ZipCode CHAR(5) NOT NULL
	)
GO

CREATE TABLE Special (
	SpecialID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Title VARCHAR(100) NOT NULL,
	SpecialDescription VARCHAR(300) NOT NULL,
	DateAdded DATETIME NOT NULL DEFAULT(GETDATE()),
	UserID NVARCHAR(128) NOT NULL
	)
GO

CREATE TABLE Make (
	MakeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MakeName VARCHAR(20) NOT NULL,
	DateAdded DATETIME NOT NULL DEFAULT(GETDATE()),
	UserID NVARCHAR(128) NOT NULL
	)
GO

CREATE TABLE Model (
	ModelID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ModelName VARCHAR(20) NOT NULL,
	MakeID INT NOT NULL FOREIGN KEY REFERENCES Make(MakeID),
	DateAdded DATETIME NOT NULL DEFAULT(GETDATE()),
	UserID NVARCHAR(128) NOT NULL
	)
GO

CREATE TABLE Vehicle (
	VehicleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	VehicleYear INT NOT NULL,
	MakeID INT NOT NULL FOREIGN KEY REFERENCES Make(MakeID),
	ModelID INT NOT NULL FOREIGN KEY REFERENCES Model(ModelID),
	Price DECIMAL(9,2) NOT NULL,
	Mileage INT NOT NULL,
	Vin CHAR(17) NOT NULL,
	MSRP DECIMAL(9,2) NOT NULL,
	VehicleDescription varchar(300) NOT NULL,
	VehicleType VARCHAR(5) NOT NULL,
	ImageFileName VARCHAR(MAX) NULL,
	BodyStyleID INT NOT NULL FOREIGN KEY REFERENCES BodyStyle(BodyStyleID),
	TransmissionID INT NOT NULL FOREIGN KEY REFERENCES Transmission(TransmissionID),
	BodyColorID INT NOT NULL FOREIGN KEY REFERENCES BodyColor(BodyColorID),
	InteriorColorID INT NOT NULL FOREIGN KEY REFERENCES InteriorColor(InteriorColorID),
	DateAdded DATETIME NOT NULL DEFAULT(GETDATE()),
	SaleStatus BIT NOT NULL,
	IsFeatured BIT NOT NULL
	)
GO

CREATE TABLE Purchase (
	PurchaseID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PurchaseType VARCHAR(20) NOT NULL,
	PurchasePrice DECIMAL(9,2) NOT NULL,
	PurchaseDate DATETIME NOT NULL DEFAULT(GETDATE()),
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
	UserID NVARCHAR(128) NOT NULL,
	SpecialID INT NULL FOREIGN KEY REFERENCES Special(SpecialID),
	VehicleID INT NOT NULL FOREIGN KEY REFERENCES Vehicle(VehicleID)
	)
GO

CREATE TABLE Contact (
	ContactID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FullName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(30) NULL,
	Phone VARCHAR(24) NULL,
	[Message] VARCHAR(300) NOT NULL,
	Vin CHAR(17) NULL,
	DateAdded DATETIME NOT NULL DEFAULT(GETDATE())
	)
GO